added doorsensor to NukiLock
pschmitt/pynuki pull request #61
Opened 2020-09-04 15:53 UTC by pree

I've added the doorsensor state & name to the NukiLock class.
I saw in a different PR that you'd like to have a NukiLockV2 object, since the doorsensor is not present on the V1 Locks.

For this reason I asked in the nuki developer forum what the Bridge-API does with V1-Locks: https://developer.nuki.io/t/door-sensor-state-on-lock-v1/7157

If it just reports as "unknown" or "deactivated" I don't see the needs to split this into two different classes.  What do you think about this?

2020-09-04 18:41 UTC, pschmitt commented
I wasn't aware that it would return "unknown". That alleviates most of my concerns.

2020-09-04 18:45 UTC, pschmitt requested changes
I'll take a look at what the v1 lock actually returns when I find the time to do so (next week probably - ping me if I forget).

2020-09-04 18:45 UTC, pschmitt commented on pynuki/lock.py
> +        self.door_sensor_state != const.STATE_DOORSENSOR_DEACTIVATED
This will return True for v1 locks.
You need to add another check for the "unknown" value.

2020-09-07 11:27 UTC, pschmitt commented
Okay, so I check with my v1 lock, here's the JSON state:

```python                
{'deviceType': 0,
 'nukiId': REPLACED,
 'name': 'Front Door',
 'firmwareVersion': '1.9.6',
 'mode': 2,
 'state': 1,
 'stateName': 'locked',
 'batteryCritical': False}
```

As you can see there is no door sensor fields. So what we really want to do in `is_door_sensor_activated` is to check for `None` as well.

2020-09-07 13:59 UTC, pree commented
Thanks for testing!

I've added Unknown & None to the check. Could you test if this is working for V1, it's working fine for V2

2020-09-15 08:11 UTC, pree commented
We've also got an official answer from NUKI that unsupported values are not included in the request. https://developer.nuki.io/t/door-sensor-state-on-lock-v1/7157/2?u=pree

2020-09-15 11:26 UTC, pschmitt commented on pynuki/lock.py
> +        )
I've tried your PR with my v1 lock.

In its current state `is_door_sensor_activated` returns `True` for my lock.
I suggest to update the method as follows:

```suggestion
    @property                                                                                  
    def is_door_sensor_activated(self):
        # Nuki v1 locks don't have a door sensor, therefore the                                
        # door_sensor_state will is unset for them.                    
        if (
            not self.door_sensor_state
            or self.door_sensor_state == const.STATE_DOORSENSOR_UNKNOWN    
        ):                                     
            return
        return self.door_sensor_state != const.STATE_DOORSENSOR_DEACTIVATED
```

2020-09-15 12:02 UTC, pree commented on pynuki/lock.py
> +        )
Perfect, I added your suggestion. When you're ready I would stash my commits and we can merge :)

2020-09-15 12:14 UTC, merged

2020-09-15 12:14 UTC, pschmitt commented on pynuki/lock.py
> +        )
I squashed the PR. Thanks for your contribution :)

2020-09-15 12:19 UTC, pschmitt commented
Included in 1.4.0: https://pypi.org/project/pynuki/1.4.0/

2020-09-16 07:37 UTC, chpego commented
Included too Nuki component HA ? :)

2020-09-16 08:11 UTC, pschmitt commented
> Included too Nuki component HA ? :)
No. Not yet. I won't be issuing a PR for this.

2020-09-22 06:31 UTC, jghaanstra commented
> I won't be issuing a PR for this.
Just wondering why it will not be included in HA?

2020-09-22 14:40 UTC, pschmitt commented
> Just wondering why it will not be included in HA?

No reason. Feel free to implement it yourself. I have no way to properly test this, that's all.

2020-09-22 16:47 UTC, pree commented
I have a rouge configuration for HA running on my RPi. I will clean it up and create a PR for HA.