added ringaction to NukiOpener
pschmitt/pynuki pull request #63
Opened 2020-10-01 09:04 UTC by pree

I've added the ringactionTimestamp & ringactionState to the NukiOpener.

This comes with the Bridge Firmware 2.7.0 & Opener Firmware 1.5.1, which are currently in Beta.
(REL: https://developer.nuki.io/t/bridge-beta-fw-2-7-x-1-17-x/6792)

2020-10-01 18:31 UTC, pschmitt requested changes
Almost lgtm ;)

2020-10-01 18:31 UTC, pschmitt commented on pynuki/opener.py
> +    def ringactionTimestamp(self):
Please use snake case


```suggestion
    def ring_action_timestamp(self):
```

2020-10-01 18:31 UTC, pschmitt commented on pynuki/opener.py
> +    def ringactionState(self):
```suggestion
    def ring_action_state(self):
```

2020-10-02 11:46 UTC, pree commented on pynuki/opener.py
> +    def ringactionTimestamp(self):
done :)

2020-10-02 16:19 UTC, merged