Added additional device properties
pschmitt/pynuki pull request #69
Opened 2021-01-11 19:19 UTC by vauriga

New properties: battery level and KeyPad battery critical

2021-01-12 07:16 UTC, pschmitt requested changes
Thanks for your contribution. See my comment in the review.

2021-01-12 07:16 UTC, pschmitt commented on pynuki/device.py
> +        return self._json.get("batteryChargeState")
I don't believe that this here is the right place for these attributes. It seems only the keypad has these. What I want to see is a dedicated class (inheriting from `pynuki.device`)

2021-01-13 01:50 UTC, vauriga commented on pynuki/device.py
> +        return self._json.get("batteryChargeState")
Hmm, but why? batteryChargeState is a battery level of the lock in percents, it shows after enabling inside Nuki App,
as for the Keypad... it's not a separate device, API returns it's battery critical state in the same json as the lock if it was paired with it. Both of those properties are part of the API response for the lock.

2021-01-13 01:58 UTC, vauriga commented on pynuki/device.py
> +        return self._json.get("batteryChargeState")
or we can move this to `lock.py`, like the `doorSensorStates`, what do you think?

2021-01-13 11:11 UTC, pschmitt commented on pynuki/device.py
> +        return self._json.get("batteryChargeState")
I was under the impression that the keypad was another `Lock` device, that just had a few keypad specific properties. If that's not the case as you suggest then moving it to `lock.py` makes more sense.

2021-01-13 11:31 UTC, vauriga commented on pynuki/device.py
> +        return self._json.get("batteryChargeState")
unfortunately no, it's just an extension to the lock and can't be used as standalone device.

2021-01-13 11:38 UTC, steinerl commented on pynuki/device.py
> +        return self._json.get("batteryChargeState")
IMO it would also be nice if the property names matched the key names in the JSON.

2021-01-13 12:01 UTC, merged