Fix device Type V3
pschmitt/pynuki pull request #81
Opened 2022-03-17 19:15 UTC by FabianKielkopf

Added support for new Devices (Gen 3 Nuki Startlocks).

2022-03-17 19:32 UTC, c0ffee commented
+1

2022-03-18 07:26 UTC, pschmitt requested changes
I'd like to have a default value set for `device_type` so that this is less of a breaking change.
Other than that: LGTM, thanks!

2022-03-18 07:26 UTC, pschmitt commented on pynuki/bridge.py
> +    def lock(self, nuki_id, device_type, block=False):
```suggestion
    def lock(self, nuki_id, device_type=const.DEVICE_TYPE_LOCK, block=False):
```

2022-03-18 07:26 UTC, pschmitt commented on pynuki/bridge.py
> +    def unlock(self, nuki_id, device_type, block=False):
```suggestion
    def unlock(self, nuki_id, device_type=const.DEVICE_TYPE_LOCK, block=False):
```

2022-03-18 07:26 UTC, pschmitt commented on pynuki/bridge.py
> +    def lock_n_go(self, nuki_id, device_type, unlatch=False, block=False):
```suggestion
    def lock_n_go(self, nuki_id, device_type=const.DEVICE_TYPE_LOCK, unlatch=False, block=False):
```

2022-03-18 07:26 UTC, pschmitt commented on pynuki/bridge.py
> +    def unlatch(self, nuki_id, device_type, block=False):
```suggestion
    def unlatch(self, nuki_id, device_type=const.DEVICE_TYPE_LOCK, block=False):
```

2022-08-04 15:55 UTC, mi1os commented
hey guys, can we please merge this? can I help with it somehow?

2023-03-21 10:53 UTC, pvizeli commented
Yeah, would be nice to having it

2023-03-25 07:28 UTC, merged